# BuildOpenBLAS.cmake - Build OpenBLAS as a static library for wheel distribution

include(ExternalProject)

set(OPENBLAS_VERSION "0.3.28")
set(OPENBLAS_URL "https://github.com/OpenMathLib/OpenBLAS/releases/download/v${OPENBLAS_VERSION}/OpenBLAS-${OPENBLAS_VERSION}.tar.gz")
set(OPENBLAS_SHA256 "f1003466ad074e9b0c8d421a204121100b0c0df6b44e0eb96c2a7a1ecaae87a9")

set(OPENBLAS_INSTALL_DIR ${CMAKE_BINARY_DIR}/openblas-install)

set(OPENBLAS_BUILD_OPTIONS
    NO_FORTRAN=1
    NO_LAPACKE=1
    USE_OPENMP=0
    USE_THREAD=1
    NUM_THREADS=64
    NO_SHARED=1
    MAKE_NB_JOBS=${CMAKE_BUILD_PARALLEL_LEVEL}
)

if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64")
        list(APPEND OPENBLAS_BUILD_OPTIONS TARGET=ARMV8 DYNAMIC_ARCH=1 DYNAMIC_OLDER=1)
    else()
        list(APPEND OPENBLAS_BUILD_OPTIONS TARGET=HASWELL DYNAMIC_ARCH=1 DYNAMIC_OLDER=1)
    endif()
    set(OPENBLAS_LIB_NAME "libopenblas.a")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|aarch64")
        list(APPEND OPENBLAS_BUILD_OPTIONS TARGET=ARMV8 DYNAMIC_ARCH=1)
    else()
        list(APPEND OPENBLAS_BUILD_OPTIONS TARGET=HASWELL DYNAMIC_ARCH=1 DYNAMIC_OLDER=1)
    endif()
    set(OPENBLAS_LIB_NAME "libopenblas.a")
else()
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
        list(APPEND OPENBLAS_BUILD_OPTIONS TARGET=ARMV8 DYNAMIC_ARCH=1 DYNAMIC_OLDER=1)
    else()
        list(APPEND OPENBLAS_BUILD_OPTIONS TARGET=HASWELL DYNAMIC_ARCH=1 DYNAMIC_OLDER=1)
    endif()
    set(OPENBLAS_LIB_NAME "libopenblas.a")
endif()

list(JOIN OPENBLAS_BUILD_OPTIONS " " OPENBLAS_BUILD_OPTIONS_STR)

ExternalProject_Add(openblas_external
    URL ${OPENBLAS_URL}
    URL_HASH SHA256=${OPENBLAS_SHA256}
    DOWNLOAD_DIR ${CMAKE_BINARY_DIR}/openblas-download
    SOURCE_DIR ${CMAKE_BINARY_DIR}/openblas-src
    BINARY_DIR ${CMAKE_BINARY_DIR}/openblas-build
    INSTALL_DIR ${OPENBLAS_INSTALL_DIR}
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ${CMAKE_COMMAND} -E env
        ${CMAKE_MAKE_PROGRAM} -C <SOURCE_DIR>
        ${OPENBLAS_BUILD_OPTIONS_STR}
        PREFIX=<INSTALL_DIR>
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} -C <SOURCE_DIR>
        ${OPENBLAS_BUILD_OPTIONS_STR}
        PREFIX=<INSTALL_DIR>
        install
    BUILD_BYPRODUCTS ${OPENBLAS_INSTALL_DIR}/lib/${OPENBLAS_LIB_NAME}
    LOG_DOWNLOAD ON
    LOG_BUILD ON
    LOG_INSTALL ON
)

add_library(OpenBLAS::OpenBLAS STATIC IMPORTED GLOBAL)
add_dependencies(OpenBLAS::OpenBLAS openblas_external)
set_target_properties(OpenBLAS::OpenBLAS PROPERTIES
    IMPORTED_LOCATION ${OPENBLAS_INSTALL_DIR}/lib/${OPENBLAS_LIB_NAME}
    INTERFACE_INCLUDE_DIRECTORIES ${OPENBLAS_INSTALL_DIR}/include
)

find_package(Threads REQUIRED)
set_property(TARGET OpenBLAS::OpenBLAS APPEND PROPERTY
    INTERFACE_LINK_LIBRARIES Threads::Threads
)

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    find_library(GFORTRAN_LIB gfortran)
    if(GFORTRAN_LIB)
        set_property(TARGET OpenBLAS::OpenBLAS APPEND PROPERTY
            INTERFACE_LINK_LIBRARIES ${GFORTRAN_LIB}
        )
    endif()
endif()

set(OPENBLAS_FOUND TRUE CACHE BOOL "OpenBLAS found" FORCE)
set(OPENBLAS_INCLUDE_DIRS ${OPENBLAS_INSTALL_DIR}/include CACHE PATH "OpenBLAS include directory" FORCE)
set(OPENBLAS_LIBRARIES OpenBLAS::OpenBLAS CACHE STRING "OpenBLAS library" FORCE)

message(STATUS "OpenBLAS will be built from source (version ${OPENBLAS_VERSION})")
